### ISSUE TITLE
Webhook for INVOICING.INVOICE.PAID does not return any Invoice data

### ISSUE THREAD

**Issue by gkachru** [paypal/PayPal-Python-SDK#182]
### General Information

- Mode: Sandbox
- PayPal-Debug-ID(s) (from any logs): NA
- Version of Python used: 2.7.12
- SDK Version: 1.12.0

### Issue Description

Webhook POST data validates correctly using WebhookEvent.verify, however it does not contain any data about the invoice itself. Please find below the response I have been getting:

```
{"id":"WH-09E65532S0903350P-6JH87154GP593045B","event_version":"1.0","create_time":"2017-01-24T20:48:07Z","resource_type":"invoices","event_type":"INVOICING.INVOICE.PAID","summary":"An invoice has been paid","resource":{"invoice":null},"links":[{"href":"https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-09E65532S0903350P-6JH87154GP593045B","rel":"self","method":"GET"},{"href":"https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-09E65532S0903350P-6JH87154GP593045B/resend","rel":"resend","method":"POST"}]}
```

Steps to reproduce:
1. Create a webhook URL in the sandbox to listen to  INVOICING.INVOICE.PAID
2. Create and send an invoice using the rest API in the sandbox
3. Use a sandbox testing buyer account to pay for the item. Alternatively, mark the invoice as paid in the sandbox UI.
4. Webhook event received contains `"resource":{"invoice":null}` and has no actually invoice data.

Notes:
- Response visible in developer portal under Sandbox > Webhook Events is the same as that received by the webhook listener.

**Comment by pp-randy** [comment]
Thank you for reporting this issue.  I am following up on this further. 

Internal Tracking: PPPLPAYPT-16756

**Comment by pp-randy** [comment]
This has been resolved.  However, the webhooks are not validating so reopening https://github.com/paypal/PayPal-PHP-SDK/issues/704

**Comment by ahzb** [comment]
We are still experiencing blank Resource and other missing data from INVOICE.PAID  webhook calls.  Is there something else we need to do to get this working ?

**Comment by pp-randy** [comment]
@ahzb can you provide the webhook you received?
